baseURL = 'https://paulo1312.github.io/'
languageCode = 'ru_RU'
title = 'Make Siberia Free Again'

theme = 'paulotheme'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Amcofixer'
pageRef = '/amcofixer'
weight = 20

[[menus.main]]
name = 'SS to json'
pageRef = '/ss_to_json'
weight = 30

[[menus.main]]
name = 'VGC Decoder'
pageRef = '/vgc_decoder'
weight = 40


[taxonomies]
  tag = 'tags'


[params]
  [params.author]
    name="paulo1312"
    email="pavel_panov@riseup.net"